### ISSUE TITLE
Image screenshot partially  hidden by ads

### ISSUE THREAD

**Issue by paulcana** [Harkame/JapScanDownloader#38]
Hello,
Thank you for your script that allowed me to get mangas from Japscan.
I noticed an issue that happens from time to time. Sometimes the screenshot taken by the script contains the ads above the manga page and manga page is partially hidden.
Would there be a way to correct this behaviour or try to run the script for individual pages after manual verification.
Thank again for your work

**Comment by paulcana** [comment]
I tested with https://adblockplus.org/ and I have few pages with ads.
I am downloading volumes with more than 200 pages and maybe around 10 are impacted.

**Comment by Harkame** [comment]
Can I have the URL of the manga/chapter to reproduce this error please ?
And please can you share an screenshot of a page hidden by ads ?

For now, maybe try an another adblocker

**Comment by paulcana** [comment]
manga is dragon-ball. I had the issue on volume-1, volume-2, 3 and 4
what I have done as a workaround as very few pages are impacted. I went to japscan site and downloaded the missing image manually.
I don't have access to the screenshot currently but I can share one later. The Ad is always at top of the screenshot and the page bottom is truncated.

**Comment by JPGrimault** [comment]
I also confirm seen the issue, i have actually installed ublock and I just got the issue today
### config: 
mangas:
  - manga: https://www.japscan.co/manga/hunter-x-hunter/

This is happening on volume 219 page 1, volume 213 page 11, and I guess many more

**Comment by Harkame** [comment]
I've updated japscandownloader, just make sure you are using 1.0.3 version

First of all, my bad, precedent version is not using adblockers because its not using user profile

I've added 2 new options 

-p, --profile : Chrome profile, Its your chrome profile (with installed plugins, adblockers, etc)
_Big inconvenient, you can't use normal chrome browser and this command at same time_

-s, --show   : Show, display browser. Just to make sure you are using your profile with plugins

Example on Windows :
`
japscandownloader -D C:\chromedriver -p "C:\Users\Me\AppData\Local\Google\Chrome\User Data" -s
`

**Comment by Harkame** [comment]
options.add_argument("--profile-directory=Default") added  by default in 1.0.4
